language: ruby
install: bundle install --path vendor/bundle
cache:
  directories: vendor/bundle
addons:
  hosts:
    - vvv.dev
    - local.wordpress.dev
    - local.wordpress-trunk.dev
    - src.wordpress-develop.dev
    - build.wordpress-develop.dev

before_script:
    - sudo rm -rf ~/.gnupg
    - sudo sudo useradd vagrant -d /home/vagrant -s /bin/bash
    - sudo mkdir /srv/database && sudo mount --bind `pwd`/database /srv/database
    - sudo mkdir /srv/config && sudo mount --bind `pwd`/config /srv/config
    - sudo mkdir /srv/www && sudo mount --bind `pwd`/www /srv/www
    - sudo chown -R vagrant:vagrant /srv/www && sudo chmod 6775 /srv/www
    - sudo cp /srv/config/mysql-config/my.cnf /etc/mysql/my.cnf
    - sudo service mysql restart && echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - sudo bash provision/provision.sh
    - ls -alF /srv/www/wordpress-trunk/

script: TARGET=localhost bundle exec rake spec
