language: ruby
install: bundle install --path vendor/bundle
cache:
  directories: vendor/bundle
addons:
  hosts:
    - vvv.dev
    - local.wordpress.dev
    - local.wordpress-trunk.dev
    - src.wordpress-develop.dev
    - build.wordpress-develop.dev

before_script:
    - ls -alF /srv/
    - sudo mkdir /srv && sudo mount --bind `pwd` /srv
    - sudo bash provision/provision.sh

script: bundle exec rake spec
